### ISSUE TITLE
Adaptations needed to support new JQuery

### ISSUE THREAD

**Issue by Christophe06410** [prashant1rana/jQWCloud#3]
Hi,

In order to support JQuery 1.9+, you need to perform below changes:
in file jQWClouV3.1.js, 

- Line 222: .live shall be replaced by .on with additional parameter as follows:
```
		$(wordObj.span).on("click",null, this.options.word_click);
                $(wordObj.span).on("mouseover", null, this.options.word_mouseOver);
                $(wordObj.span).on("mouseout", null, this.options.word_mouseOut);
                $(wordObj.span).on("mouseenter", null, this.options.word_mouseEnter);

```
- line 449: browser is not supported. Removed support for IE:

```
case VR:
			var span=word.span;
			//IE Handling for Differenet way of Rotation Transforms 
			//if(jQuery.browser.msie){
			//	$(span).css("left",obj.x + xMul*h).css("top", obj.y + yMul*w);
			//}else{
				$(span).css("left",obj.x + xMul*h - (w-h)/2).css("top", obj.y + yMul*w + (w-h)/2);							
			//}	

```
Please perfrom changes to get up to date regarding Jquery.
I attached corresponding js file.
Thanks.
Christophe
[jQWCloudv3.1.zip](https://github.com/prashant1rana/jQWCloud/files/3879797/jQWCloudv3.1.zip)

**Comment by prashant1rana** [comment]
Thanks for all details.I have committed the updated files in new branch.
